module.exports = {
    DB: process.env.DB || "",
    PORT: process.env.PORT || "3000",
    IS_CONSOLE_LOG: process.env.IS_CONSOLE_LOG || "true",
    AMQP_HOST_URL: process.env.AMQP_HOST_URL || "",
    WS_URL: process.env.WS_URL || "wss://ws.apothem.network",
    SYNC_BLOCK_EXCHANGE: process.env.SYNC_BLOCK_EXCHANGE || "sync-block-exchange",
    SYNC_BLOCK_QUEUE: process.env.SYNC_BLOCK_QUEUE || "sync-block-queue",
    SYNC_TRANSACTION_EXCHANGE: process.env.SYNC_TRANSACTION_EXCHANGE || "sync-transaction-exchange",
    SYNC_TRANSACTION_QUEUE: process.env.SYNC_TRANSACTION_QUEUE || "sync-transaction-queue",
    SYNC_ACCOUNT_EXCHANGE: process.env.SYNC_ACCOUNT_EXCHANGE || "sync-account-exchange",
    SYNC_ACCOUNT_QUEUE: process.env.SYNC_ACCOUNT_QUEUE || "sync-account-queue",
    SYNC_CONTRACT_EXCHANGE: process.env.SYNC_CONTRACT_EXCHANGE || "sync-contract-exchange",
    SYNC_CONTRACT_QUEUE: process.env.SYNC_CONTRACT_QUEUE || "sync-contract-queue",
    SYNC_TOKEN_EXCHANGE: process.env.SYNC_TOKEN_EXCHANGE || "sync-token-exchange",
    SYNC_TOKEN_QUEUE: process.env.SYNC_TOKEN_QUEUE || "sync-token-queue",
    SYNC_TRANSFER_EXCHANGE: process.env.SYNC_TRANSFER_EXCHANGE || "sync-transfer-exchange",
    SYNC_TRANSFER_QUEUE: process.env.SYNC_TRANSFER_QUEUE || "sync-transfer-queue",
    SYNC_TOKEN_HOLDER_QUEUE: process.env.SYNC_TOKEN_HOLDER_QUEUE || "sync-token-holder-queue",
    SYNC_TOKEN_HOLDER_EXCHANGE: process.env.SYNC_TOKEN_HOLDER_EXCHANGE || "sync-token-holder-exchange",
    ORIGIN_URL: process.env.ORIGIN_URL || "http://localhost:3000",
    RDS_FILE: process.env.RDS_FILE || "",
    IS_LATEST_SYNC_ENABLE: process.env.IS_LATEST_SYNC_ENABLE || false,
    IS_LAST_SYNC_ENABLE: process.env.IS_LAST_SYNC_ENABLE || false,
    RANGE_FIRST_BLOCK: process.env.RANGE_FIRST_BLOCK || 34000000,
    RANGE_LAST_BLOCK: process.env.RANGE_LAST_BLOCK || 36000000,
    BUCKET_RANGE: process.env.BUCKET_RANGE || 50000,
    CHECK_BLOCK_IN_DB:process.env.CHECK_BLOCK_IN_DB||true
};
